# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://doughnutlounge.com
title: Doughnut Lounge
email: your-email@domain.com
description: "The Doughnut Lounge is slapping you in the mouth with flavor soon and putting doughnuts on the map in KC – Follow us, share us, retweet us!"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/doughnutlounge
  - title: instagram
    url: https://instagram.com/doughnutlounge
